In [5]:
j_test = """{"area": 7420,"bedrooms": 4,"bathrooms": 2,"stories": 2,"mainroad": "yes","guestroom": "no","basement": "no","hotwaterheating": "no","airconditioning": "yes","parking": 2,"prefarea": "yes","furnishingstatus": "furnished"}"""

In [23]:
import joblib
import json
import sklearn as sk
import pandas as pd
model = joblib.load("linear_model.joblib")

In [24]:
input = json.loads(j_test)

In [25]:
input

{'area': 7420,
 'bedrooms': 4,
 'bathrooms': 2,
 'stories': 2,
 'mainroad': 'yes',
 'guestroom': 'no',
 'basement': 'no',
 'hotwaterheating': 'no',
 'airconditioning': 'yes',
 'parking': 2,
 'prefarea': 'yes',
 'furnishingstatus': 'furnished'}

In [26]:
df = pd.DataFrame(input, index=[0])

In [27]:
df

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,7420,4,2,2,yes,no,no,no,yes,2,yes,furnished

In [28]:
mp = {'no': 0, 'yes': 1, 'furnished': 1, 'semi-furnished': 0.5, 'unfurnished': 0}
clas = ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea', 'furnishingstatus']
for i in clas:
    df[i] = df[i].map(mp)
df.head()

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,7420,4,2,2,1.0,0.0,0.0,0.0,1.0,2,1.0,1.0

In [29]:
model.predict(df)

array([7597849.24707712])